
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Perfumaria', 'Artigos em perfumaria')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Condimentos', 'Alimentos em geral')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Masas', 'Massas em geral')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Oleos', 'Oleos em geral')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Farinhas', 'Farinhas em geral')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Bebidas', 'Bebidas em geral')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Limpeza', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Higiene Pessoal', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Vestuário', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Laticinios', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Biscoitos', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Carnes', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Pães', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Frios', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Hortifrutis', '')
INSERT INTO dbo.categoria (categoria, descricaoCat)
VALUES ('Geral', '')